### ISSUE TITLE
邮箱正则匹配太简单

### ISSUE THREAD

**Issue by gavinfish** [junicorn/java-china#20]
注册账号时不支持邮箱账号类型： \*.\*@gmail.com

**Comment by zh-h** [comment]
那看来我的outlook也不能咯

**Comment by biezhi** [comment]
实际上都可以的

**Comment by biezhi** [comment]
已经修复 https://github.com/junicorn/java-china/commit/cfc3d28122c463ab1768421a91eed29678a831dc
