### ISSUE TITLE
注销问题！

### ISSUE THREAD

**Issue by icevb6** [junicorn/java-china#21]
无法注销。response.go("/")没反应，并且感觉session好像删除后，又登录了。

**Comment by biezhi** [comment]
你是指 http://java-china.org/ 这里登陆注销不了，还是你本地运行无法注销。

**Comment by icevb6** [comment]
谢谢，即时回复!是本地运行！

**Comment by biezhi** [comment]
@icevb6 可以详细说一下你的运行环境吗？我在本地和外网都有测试过没问题的。你的配置文件贴一下，web服务器是tomcat吗？

**Comment by icevb6** [comment]
# base package
blade.basepackage = com.javachina
blade.dev = true

blade.view.500 = /500.html
blade.view.404 = /404.html

app.version = 0.1.3
app.site_url = http://127.0.0.1:8080/java-china
app.db_cahce = false
app.aes_salt = javacina

# \u540D\u8A00\u63A5\u53E3key
famous.key = 
# qiniu
qiniu.BUCKET_NAME = 
qiniu.ACCESS_KEY = 
qiniu.SECRET_KEY = 
qiniu.cdn = http://7xsk2r.com2.z0.glb.qiniucdn.com

# github
github.CLIENT_ID = 
github.CLIENT_SECRET = 
github.REDIRECT_URL = 

# email
app.mail.host = smtp.qq.com
app.mail.nick = Java\u4E2D\u56FD
app.mail.user = support@java-china.org
app.mail.pass = ***************
app.mail.admin = support@java-china.org

# db
jdbc.driver = com.mysql.jdbc.Driver
jdbc.url = jdbc\:mysql\://127.0.0.1\:3308/javachina?useUnicode\=true&amp;characterEncoding\=UTF-8
jdbc.user =root
jdbc.pass =root

基本没改。

tomcat7+jdk7

**Comment by icevb6** [comment]
blade是我自己编译的，不知道有问题否？因为mvn上没有你的这个版本！

**Comment by biezhi** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cblade-core

**Comment by icevb6** [comment]
我找到问题了
在ServletResponse，这里覆盖了cookie
      @Override
	public Response removeCookie(String name) {
		Cookie cookie = new Cookie(name, "");
        cookie.setMaxAge(0);
        response.addCookie(cookie);
		return this;
	}

但是在BaseInterceptor里，获取cookie的时候。
String val = SessionKit.getCookie(request, Constant.USER_IN_COOKIE);

获取出来竟然有值。

@biezhi 问题：
response.addCookie未覆盖呢？还是点击注销的时候，又将原来的Cookie赋值给Constant.USER_IN_COOKIE呢？

**Comment by icevb6** [comment]
不用cookie就可以，只用session

String val ="";// SessionKit.getCookie(request, Constant.USER_IN_COOKIE);

**Comment by biezhi** [comment]
https://github.com/junicorn/java-china/commit/cb85a5b98c32fd6d8f42da0917bb41452ee0b2f4
