### ISSUE TITLE
请问你们使用了怎么样的缓存方法？

### ISSUE THREAD

**Issue by zh-h** [junicorn/java-china#22]
[spring-abc.xyz](http://spring-abc.xyz/) 我这里是一个用 Spring 编写的社区，就是查询帖子列表的时候有  N+1 查询的问题。怎么样去用缓存解决问题呢？比如显示帖子列表的每一个最后回复。

**Comment by biezhi** [comment]
@zh-h 分表了，帖子表存储帖子基础信息，有个元信息表存点赞，评论这些。
