### ISSUE TITLE
邮件确认无法收到

### ISSUE THREAD

**Issue by miaoihan** [junicorn/java-china#26]
1. 注册了收不到邮件，qq gmail outlook 都试了
2. 主页右边栏图片溢出了

**Comment by biezhi** [comment]
1. 邮件发送的问题马上解决，51期间过节没时间呢
2. 尽快解决

感谢你的反馈  😄

**Comment by miaoihan** [comment]
java一直没有像ruby-china那样的论坛，这个不错 -_-
