### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by zjqgithub** [junicorn/java-china#27]
启动时报错
java.lang.NullPointerException
	com.blade.web.DispatcherServlet.service(DispatcherServlet.java:136)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by biezhi** [comment]
1. 检查你的代码是否是最新的(最新的在github直接下载)
2. 检查你是否导入了数据库
3. 如果都不行给一个详细的错误我帮你看看
