### ISSUE TITLE
SEC7113: CSS 因 Mime 类型不匹配而被忽略 引发的改造

### ISSUE THREAD

**Issue by icevb6** [junicorn/java-china#30]
ie9 错误：
SEC7113: CSS 因 Mime 类型不匹配而被忽略 
main.min.css?ver=0.1.3

chrome：
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:8678/iCellZoology/assets/styles/main.min.css?ver=0.1.3".

百度了一下，此问题，应该需要在response的按照 后缀名 （.css） 设置 text/css

研究了一下源码：

DispatcherHandler 中 print的时候设置一下？是否正确？还需要作者考虑一下。

方案：
可以根据web.xml里的配置来进行设置。
“<mime-mapping>
		<extension>css</extension>
		<mime-type>text/css</mime-type>
</mime-mapping>“

不知道能否修正这个问题，如果加载远程的css （配置成您官方的https://java-china.org/assets/styles/main.min.css不会出现问题）是没有问题的，但放到本地加载会出现此问题。

谢谢！！！！！

**Comment by biezhi** [comment]
这算是个框架的bug，可以提到 https://github.com/biezhi/blade/issues/new
