### ISSUE TITLE
请求不断重复提交

### ISSUE THREAD

**Issue by gaoao1205** [junicorn/java-china#34]
![qq 20160905003724](https://cloud.githubusercontent.com/assets/13028212/18232380/0c85801e-7301-11e6-9154-255dfcb009a7.png)
![qq 20160905003754](https://cloud.githubusercontent.com/assets/13028212/18232381/0cafaa56-7301-11e6-80ad-7fe2560541a4.png)

项目部署成功之后可以访问首页，但是点击其他请求之后，一直重复提交请求，一秒钟发出十几次请求

**Comment by biezhi** [comment]
你是如何操作的，目前还没有发现这种情况，或者把你的程序发到我邮箱一份，我跑起来试试

**Comment by gaoao1205** [comment]
代码是昨天在github上克隆的，按照上面的介绍的步骤修改
创建数据库，导入sql
修改配置文件
maven打war包
部署，启动tomcat，进入首页 http://127.0.0.1:8080/  正常
                           点击任意按钮，出现重复刷新，不断向后台请求数据
控制台有报错，好像是跨域问题引起的，但是没找到原因，麻烦帮帮忙看一看
控制台错误：
XMLHttpRequest cannot load http://127.0.0.1:8080/java-china/check_notice. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
