### ISSUE TITLE
build path显示有数个jar包确实，但打开相应路径发现jar包是有的！

### ISSUE THREAD

**Issue by haoning7788** [junicorn/java-china#43]
![image](https://cloud.githubusercontent.com/assets/19164051/21747230/f3b40e64-d59a-11e6-9966-65ea1f58845c.png)
麻烦给看下，谢谢！

**Comment by biezhi** [comment]
重新导入一下呢？

**Comment by biezhi** [comment]
更新代码即可，已修复
