### ISSUE TITLE
建议加入编辑器

### ISSUE THREAD

**Issue by liujkang** [junicorn/java-china#44]
类似于百度editor,http://ueditor.baidu.com/website/index.html 提供更丰富的文档输入

**Comment by biezhi** [comment]
javachina是一个轻量级论坛程序，我们希望用户输入简单的markdown语法即可表达内容，富文本编辑器不符合设计理念 : )

**Comment by cikai** [comment]
@biezhi  近期开发中帖子发布增加了bootstrap风格的 [ckeditor](http://ckeditor.com/)，同响应式设计，如有需要可贡献代码。

**Comment by biezhi** [comment]
@cikai 感谢你的建议，我们可以加入富文本编辑器进来，但是论坛没有打算为用户提供存储的功能，所以也是无法上传附件/图片的。你觉得 [summernote](http://summernote.org/) 这款编辑器如何呢？

**Comment by cikai** [comment]
@biezhi  Hi，看了一下 [summernote](http://summernote.org/)，和 [ckeditor](http://ckeditor.com/) 相比，它使用时更方便，功能更全，用户体验更好，感谢推荐   :+1: :+1:
