### ISSUE TITLE
使用github账户登陆时服务器出错。

### ISSUE THREAD

**Issue by XiaodongDu** [junicorn/java-china#5]
如题~

**Comment by biezhi** [comment]
@XiaodongDu 等发布到正式版再注册哦。邮箱服务器配置还需要调整。

**Comment by XiaodongDu** [comment]
@biezhi 原来是这样~

**Comment by biezhi** [comment]
@XiaodongDu 今天会修复好的。谢谢支持 :smile:

**Comment by XiaodongDu** [comment]
@biezhi 不用谢，应该的。:smile: 一直在向您学习。

**Comment by biezhi** [comment]
@XiaodongDu 可以试试了

**Comment by d87335903** [comment]
使用github账户登陆,好像不行,还是登陆不了

**Comment by biezhi** [comment]
@d87335903 使用github账号登录也需要绑定一个账户并激活，后面会简化这块的功能
